### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by feihuohua** [LoveZYForever/HXWeiboPhotoPicker#1]
1.点击拍照按钮，进入拍照页面，点击右上角——摄像头反转按钮，直接崩溃

2.拍照时时正方形窗口，拍出来的照片确实长方形，并且两边收窄了，不知道是什么原因

3.建议：拍照按钮，也可以在外面以UIAlertSheet的方式显示拍照功能

**Comment by LoveZYForever** [comment]
真机还是模拟器?

**Comment by LoveZYForever** [comment]
最新版 已经添加 拍照按钮 外置 以UIAlertSheet 方式弹出功能
