### ISSUE TITLE
为什么设置goCamera = yes  不是先进去照相机页面

### ISSUE THREAD

**Issue by yushan023** [LoveZYForever/HXWeiboPhotoPicker#12]
现在是先进去HXPhotoViewController  然后再进去HXCameraViewController

**Comment by yushan023** [comment]
还有个bug，在设置了goCamera以后，第二次进入，不会打开照相机了。
还有就是，清空了HXPhotoView中的照片，进去也不会打开照相机。

**Comment by LoveZYForever** [comment]
那个属性在进去之后给重置了. 你要在点击跳转相册前面加上 goCamera = YES;
