### ISSUE TITLE
请问如何设置拍照后的照片自动保存到本地?

### ISSUE THREAD

**Issue by AlasKuNull** [LoveZYForever/HXWeiboPhotoPicker#13]
在demo里面 和 文件里面没有找到相关接口

**Comment by LoveZYForever** [comment]
现在暂不支持保存拍照的照片

**Comment by LoveZYForever** [comment]
最新版已添加属性控制是否需要将拍照的图片或视频保存到系统相册
/**
 *  拍摄的 照片/视频 是否保存到系统相册  默认NO 此功能需要配合 监听系统相册 和 缓存相册 功能 (请不要关闭)
 */
BOOL saveSystemAblum;

**Comment by AlasKuNull** [comment]
谢谢！




发自网易邮箱大师
在2017年08月08日 21:19，LoveZYForever 写道：

最新版已添加属性控制是否需要将拍照的图片或视频保存到系统相册
/**

拍摄的 照片/视频 是否保存到系统相册 默认NO 此功能需要配合 监听系统相册 和 缓存相册 功能 (请不要关闭)
*/
BOOL saveSystemAblum;
