### ISSUE TITLE
pod 的情况下，效果有问题，

### ISSUE THREAD

**Issue by weizhangCoder** [LoveZYForever/HXWeiboPhotoPicker#14]
楼主写的这个很是牛逼啊，就是pod下面加载图片的路径已经[UIImage imageNamed:@"compose_delete@2x.png"]，应该不是这样的了。

**Comment by LoveZYForever** [comment]
什么?

**Comment by weizhangCoder** [comment]
就是Cocoapods：pod 'HXWeiboPhotoPicker' '~> 1.2' 这样导入，里面所有的图片显示不出来，图片的加载路径已经变了。

**Comment by LoveZYForever** [comment]
电脑的cocoapods用不了,你说的路径这个问题怎么解决?

**Comment by weizhangCoder** [comment]
举个例子。你看下pod的需要这么加载那些自带素材
+ (NSBundle *)hs_Bundle
{
    static NSBundle *hs_Bundle = nil;
    if (nil == hs_Bundle) {
        hs_Bundle = [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"HSSetTableViewController" ofType:@"bundle"]];
        
        if (nil == hs_Bundle) {
             hs_Bundle = [NSBundle bundleWithPath:[[NSBundle bundleForClass:[HSBaseTableViewCell class]] pathForResource:@"HSSetTableViewController" ofType:@"bundle"]];
        }
    }
    return hs_Bundle;
}

+ (UIImage *)hs_imageNamed:(NSString *)name
{
    CGFloat scale = [[UIScreen mainScreen] scale];
    name = 3.0 == scale ? [NSString stringWithFormat:@"%@@3x.png", name] : [NSString stringWithFormat:@"%@@2x.png", name];
    UIImage *image = [UIImage imageWithContentsOfFile:[[[NSBundle hs_Bundle] resourcePath] stringByAppendingPathComponent:name]];
    return image;
}

**Comment by LoveZYForever** [comment]
demo里拖了sd之后, 上传cocopods就一直失败..有办法解决么
