### ISSUE TITLE
相册向下偏移64

### ISSUE THREAD

**Issue by weizhangCoder** [LoveZYForever/HXWeiboPhotoPicker#17]
有没有和我遇见一样的情况，demo2的选择相册，然后整个相册向下偏移了64.？？？？？？？

**Comment by deanli08** [comment]
遇到了 在真机上向下移动了64 然后把Controller 里面的UICollectionView 里面contentInset
 改成0就可以

**Comment by LoveZYForever** [comment]
因为demo里设置这两个属相
self.navigationController.navigationBar.translucent = NO;
self.automaticallyAdjustsScrollViewInsets = YES;
