### ISSUE TITLE
选择图片的问题

### ISSUE THREAD

**Issue by anrui** [LoveZYForever/HXWeiboPhotoPicker#18]
进入大图，点击右上取消按钮取消当前选择图片，点下一步，返回主页面还是会有刚才的图片，没有取消掉。

**Comment by LoveZYForever** [comment]
已修改,请下载最新版.

**Comment by anrui** [comment]
![Uploading 1.png…]()
![Uploading 2.png
![Uploading 3.png…]()
![Uploading 1.png…]()

**Comment by anrui** [comment]
<img width="375" alt="1" src="https://cloud.githubusercontent.com/assets/7828715/26749077/4769604a-4837-11e7-85c3-38f0cf4442c9.png">
<img width="375" alt="2" src="https://cloud.githubusercontent.com/assets/7828715/26749082/511e29f4-4837-11e7-967e-8f8c5b65de9c.png">
<img width="375" alt="3" src="https://cloud.githubusercontent.com/assets/7828715/26749086/5a6683d0-4837-11e7-9eac-c7c6345c4732.png">

**Comment by LoveZYForever** [comment]
当时故意留成这个样的..... 等下我改成和微博那样,, 当只有一张照片都没选的时候点下一步才会加进去
