### ISSUE TITLE
demo2的图片回显是怎么做的呢？

### ISSUE THREAD

**Issue by zhj1002** [LoveZYForever/HXWeiboPhotoPicker#19]
demo2 的图片回显 很清晰 
但是 我是 如何获取 图片这种清洗图片呢

我原本 获取 model.thumbPhoto  但是图片很模糊

后来这样写

- (void)photoViewControllerDidNext:(NSArray *)allList Photos:(NSArray *)photos Videos:(NSArray *)videos Original:(BOOL)original
{
    
//    
//    dispatch_sync(dispatch_get_main_queue(), ^{
        [HXPhotoTools fetchOriginalForSelectedPhoto:photos completion:^(NSArray<UIImage *> *images) {
            
            for(int i = 0; i < images.count; i++) {

              // start 图片 压缩 放入 沙盒
                NSString *imgPath = [self saveImage: images[i] name:[NSString stringWithFormat:@"%@%lu",[self getTime:nil] ,(unsigned long)_imgArr.count]];
                [_imgArr addObject: imgPath];
              // end  图片 压缩 放入 沙盒

            }
            _manager = nil;
        }];

//    });

    
}

但这是个 异步 的 有时候 回显的图片还没处理好 回显就是失败了 如果加同步锁 很消耗时间

有啥 好的方法么

**Comment by LoveZYForever** [comment]
新版demo里 HXPhotoTools 里面有个方法可以获取原图image
