### ISSUE TITLE
请问这个图片浏览器能浏览网络图片吗

### ISSUE THREAD

**Issue by mgv5** [LoveZYForever/HXWeiboPhotoPicker#2]
请问这个图片浏览器能浏览网络图片吗？

**Comment by LoveZYForever** [comment]
不好意思,不支持浏览网络图片.  需要你自己改内部代码

**Comment by mgv5** [comment]
我有一个建议，你可以考虑一下，可以在你那个浏览图片控件上加上浏览网络图片的功能，然后可以把这部分单独抽出来做成一个框架。

**Comment by LoveZYForever** [comment]
暂时没有时候想这个问题. 以后会考虑一下

**Comment by LoveZYForever** [comment]
关于你说的浏览网络图片的功能已加,不过没上上传到Github .  你可以加到群里去下载看看
