### ISSUE TITLE
HXPhotoSubViewCell问题

### ISSUE THREAD

**Issue by doomc** [LoveZYForever/HXWeiboPhotoPicker#23]
你的HXPhotoSubViewCell  SDWebImage方法 [self.imageView sd_setImageWithURL:[NSURL URLWithString:self.model.networkPhotoUrl] placeholderImage:self.model.thumbPhoto options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) 爆红

**Comment by doomc** [comment]
还有demo3 有时会崩溃

**Comment by LoveZYForever** [comment]
#22

**Comment by LoveZYForever** [comment]
怎么崩溃?

**Comment by doomc** [comment]
就是添加照片，删除照片反复操作demo3就可能会崩溃

**Comment by LoveZYForever** [comment]
选完图片的回调中加了请求数组图片URL和image,会消耗cpu。一直重复请求cpu就爆了所以崩溃。Demo里写的只是给你们看的。那些请求资源的方法不是放在回调那的，应该是需要上传的时候才调那些方法。

**Comment by doomc** [comment]
我怎么获取到图片的全路径图片数组;

**Comment by LoveZYForever** [comment]
/**
 将HXPhotoModel模型数组转化成HXPhotoResultModel模型数组  - 已按选择顺序排序
 !!!!  必须是全部类型的那个数组  !!!!
 @param selectedList 已选的所有类型(photoAndVideo)数组
 @param complete 各个类型HXPhotoResultModel模型数组
 */
+ (void)getSelectedListResultModel:(NSArray<HXPhotoModel *> *)selectedList complete:(void (^)(NSArray<HXPhotoResultModel *> *alls, NSArray<HXPhotoResultModel *> *photos, NSArray<HXPhotoResultModel *> *videos))complete;

转换成HXPhotoResultModel这个模型里面有路径这个属性

**Comment by doomc** [comment]
感谢你的耐心回答 问题已解决，3q

在 2017-08-15 14:45:50，"LoveZYForever" <notifications@github.com> 写道：


/**
将HXPhotoModel模型数组转化成HXPhotoResultModel模型数组 - 已按选择顺序排序
!!!! 必须是全部类型的那个数组 !!!!
@Param selectedList 已选的所有类型(photoAndVideo)数组
@Param complete 各个类型HXPhotoResultModel模型数组
*/

(void)getSelectedListResultModel:(NSArray<HXPhotoModel *> *)selectedList complete:(void (^)(NSArray<HXPhotoResultModel *> *alls, NSArray<HXPhotoResultModel *> *photos, NSArray<HXPhotoResultModel *> *videos))complete;

转换成HXPhotoResultModel这个模型里面有路径这个属性

**Comment by xiaohange** [comment]
单选的照片如何获得路径?
