### ISSUE TITLE
关于拍照之后显示的问题

### ISSUE THREAD

**Issue by BigH2OB** [LoveZYForever/HXWeiboPhotoPicker#25]
点击拍照之后，随便拍一张照片，然后点击右方向图标，页面转场完成后，自动帮忙选择了一张照片，但是怕的照片不是这张，提个需求，连拍模式

**Comment by LoveZYForever** [comment]
调取的系统相机好像没有连拍这个功能..自动帮选的是没有保存到系统相册的,在拍完封成模型时设置了已选不会出现错乱的现象
