### ISSUE TITLE
iOS8适配问题

### ISSUE THREAD

**Issue by fanglinwei** [LoveZYForever/HXWeiboPhotoPicker#27]
在iOS8系统下运行打开相册会在HXPhotoViewController.m中
`
self.isCapabilityAvailable = self.traitCollection.forceTouchCapability == UIForceTouchCapabilityAvailable;
`

这句代码会报错

因为
`
@property (nonatomic, readonly) UIForceTouchCapability forceTouchCapability NS_AVAILABLE_IOS(9_0); // unspecified: UIForceTouchCapabilityUnknown
`

判断一下版本,可以运行出来  会出什么问题吗
`
    if (iOS9Later) {
        self.isCapabilityAvailable = self.traitCollection.forceTouchCapability == UIForceTouchCapabilityAvailable;
    }
`

**Comment by LoveZYForever** [comment]
不会,这个是判断能不能用3DTouch功能的..

**Comment by LoveZYForever** [comment]
问题已修复,感谢你提的这个Issues
