### ISSUE TITLE
CocoaPods集成问题

### ISSUE THREAD

**Issue by liuchunlao** [LoveZYForever/HXWeiboPhotoPicker#28]
指定版本号后会报错，找不到
[!] Unable to find a specification for `HXWeiboPhotoPicker~> 2.0.6`
不指定版本号 显示安装的是1.2版
Installing HXWeiboPhotoPicker (1.2)
CocoaPods上的库该升级了额。

框架很赞！

**Comment by LoveZYForever** [comment]
![image](https://user-images.githubusercontent.com/18083149/29815285-ade52710-8ce2-11e7-9846-9da66436271d.png)

**Comment by LoveZYForever** [comment]
终端执行 ```pod repo update``` 更新一下看看

**Comment by ench44** [comment]
你不要复制作者写的, 你复制 pod search 到的那一句就好了

**Comment by liuchunlao** [comment]
- 执行：pod setup
- 移除search_index.json文件： rm ~/Library/Caches/CocoaPods/search_index.json
- 执行：pod search xxx

问题解决，谢谢！
