### ISSUE TITLE
HXPhotoView嵌套在子view中添加图片问题

### ISSUE THREAD

**Issue by fanglinwei** [LoveZYForever/HXWeiboPhotoPicker#29]
HXPhotoView直接添加在controller中
设置frame
`photoView.frame = CGRectMake(12, 100, width - 24, 0);`
是可以点击添加
但是
如果把HXPhotoView嵌套在子view中
`photoView.frame = CGRectMake(12, 100, width - 24, 0);`
这样设置点击加号添加图片,走不到cell点击的这个方法
`- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath `

如果把HXPhotoView嵌套在子view中photoView.frame这样设置
`photoView.frame = CGRectMake(12, 100, width - 24, 84);`
就可以走到点击cell的方法来

如果把HXPhotoView添加在在controller的ChildViewController的view中  无论如何怎么设置frame都走不到cell点击方法了

但是都可以正常的显示出来 

我的项目是一个多层级嵌套界面,不管怎么添加都点击不了

**Comment by LoveZYForever** [comment]
你加下我QQ,这样我看不明白..
