### ISSUE TITLE
代理方法遍历数组，获取图片二进制，为空

### ISSUE THREAD

**Issue by yushan023** [LoveZYForever/HXWeiboPhotoPicker#3]
![Uploading A954244B-B7C9-4773-821D-9C20BA359045.png…]()

- (void)photoViewChangeComplete:(NSArray *)allList Photos:(NSArray *)photos Videos:(NSArray *)videos Original:(BOOL)isOriginal
{
    NSLog(@"%ld - %ld - %ld",allList.count,photos.count,videos.count);
    NSLog(@"%@",photos);
    [allList enumerateObjectsUsingBlock:^(HXPhotoModel *photo, NSUInteger idx, BOOL *stop) {
        NSLog(@"%@",photo.imageData);
    }];

}
此方法打印图片二进制位空

**Comment by LoveZYForever** [comment]
要根据模型里面PHAsset对象去取出你要想到东西 , 直接拿模型里面的值 话,有的是没有的
