### ISSUE TITLE
直接使用HXPhotoViewController选择图片后在代理方法里面布局，图片顺序不正确

### ISSUE THREAD

**Issue by wenshao1018** [LoveZYForever/HXWeiboPhotoPicker#34]
- (HXPhotoManager *)manager
{
    if (!_manager) {
        _manager = [[HXPhotoManager alloc] initWithType:HXPhotoManagerSelectedTypePhotoAndVideo];
        _manager.openCamera = YES;
        _manager.cacheAlbum = YES;
        _manager.lookLivePhoto = YES;
        _manager.open3DTouchPreview = YES;
        _manager.cameraType = HXPhotoManagerCameraTypeSystem;
        _manager.photoMaxNum = 6;
        _manager.maxNum = 6;
        _manager.saveSystemAblum = NO;
    }
    return _manager;
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    HXPhotoViewController *vc = [[HXPhotoViewController alloc] init];
    vc.delegate = self;
    vc.manager = self.manager;
    [self presentViewController:[[UINavigationController alloc] initWithRootViewController:vc] animated:YES completion:nil];
}

- (void)photoViewControllerDidNext:(NSArray<HXPhotoModel *> *)allList Photos:(NSArray<HXPhotoModel *> *)photos Videos:(NSArray<HXPhotoModel *> *)videos Original:(BOOL)original
{
    [HXPhotoTools getImageForSelectedPhoto:photos type:HXPhotoToolsFetchHDImageType completion:^(NSArray<UIImage *> *images) {
        //这里的images数组顺序不是我之前选择的，多张选择才会出现这个问题，一张一张选择是不会出现问题，用UIImageView显示出来的结果，已经变顺序了。
    }];
}

代理方法里面拿到的images数组，里面的顺序不是我自己之前选择的顺序，求解决，很无语，不知道怎么解决。

**Comment by wenshao1018** [comment]
![Uploading xianshi.png…]()
![Uploading xuanze.png…]()

选择是按照顺序1 2 3 4 5这样选择的，但是最后排序的结果不是我之前的1 2 3 4 5这样排序。

**Comment by wenshao1018** [comment]
![Uploading xuanze.png…]()
![Uploading xianshi.png…]()
选择是按照顺序1 2 3 4 5这样选择的，但是最后排序的结果不是我之前的1 2 3 4 5这样排序。

**Comment by wenshao1018** [comment]
再次点击，弹出HXPhotoViewController后，直接点击确定返回，数组顺序又正确了，求解决。

**Comment by LoveZYForever** [comment]
下一版本会优化一下这个功能
