### ISSUE TITLE
设置UIManager，这个getImage方法加入字典那里crash

### ISSUE THREAD

**Issue by Toxic-YX** [LoveZYForever/HXWeiboPhotoPicker#37]
更改HXPhotoManager的HXPhotoUIManager，这个资源会出错误
- (void)getImage字典加入资源会crash。

**Comment by LoveZYForever** [comment]
有图片没设，或者图片是空的原因

**Comment by LoveZYForever** [comment]
v2.0.8 版本修改了这里 直接更改的话不会出现空的了
