### ISSUE TITLE
拍摄过的视频保存在沙盒里面了吗,导致APP的占用储存越来越大,大神能否提供个方法上传完视频后如何清理.

### ISSUE THREAD

**Issue by kimving** [LoveZYForever/HXWeiboPhotoPicker#39]
拍摄过的视频保存在沙盒里面了吗,导致APP的占用储存越来越大,大神能否告知上传完视频后如何清理存储的视频

**Comment by LoveZYForever** [comment]
都是临时文件下次就没了

**Comment by kimving** [comment]
那是要把APP杀死再进去,那些视频数据就自动删除了吗?但是我试过了,并没有删除哦,APP的缓存数据还是很大,并不等于原始APP大小,而且拍摄的视频越多APP的文稿和数据就越来越大,下次进去还是会有,今天我的测试机拍摄不了视频了我才知道存储被用完了才导致拍摄不了

**Comment by LoveZYForever** [comment]
刚刚才发现仿微博的那个相机界面拍摄的视频裁剪视频的时候路径写错了...

**Comment by LoveZYForever** [comment]
HXCameraViewController.m    1044行    换成下面这样保存到临时目录里....
``` NSString *myPathDocs =  [NSTemporaryDirectory() stringByAppendingPathComponent:
                             [NSString stringWithFormat:@"FinalVideo-%d.mov",arc4random() % 1000]];```

**Comment by kimving** [comment]
恩,我还发现个小问题,当_manager.saveSystemAblum = YES;的时候,通过相机拍摄视频的的回调里面的model.videoURL是空,当_manager.saveSystemAblum = NO的时候才有值,楼主我有个建议不知可不可行,当_manager.saveSystemAblum = YES的时候播放视频或者回调都采用视频在相库里面的路径,就不需要保存在临时文件了,当_manager.saveSystemAblum = NO的时候才采用保存临时文件

**Comment by telami** [comment]
PhotoTools.removeCache()

可以这样清理
