### ISSUE TITLE
设置最大图片数的bug

### ISSUE THREAD

**Issue by yushan023** [LoveZYForever/HXWeiboPhotoPicker#4]
![5212a0eb6715dcd05d1849ee4fab1947](https://cloud.githubusercontent.com/assets/20593532/23857521/96c14354-0838-11e7-85d0-d02e65132735.jpg)

设置了最大图片数为4张的时候   demo2 的最后一个按钮没有隐藏
_manager.photoMaxNum = 4;

点击加号，可进入选择相册页面，点击照相机，就报照片数上限

**Comment by LoveZYForever** [comment]
还有个视频的位置. 你视频最大数没设置 默认1.

**Comment by yushan023** [comment]
谢谢
