### ISSUE TITLE
iCloud上的视频无法下载到本地

### ISSUE THREAD

**Issue by KingQinchn** [LoveZYForever/HXWeiboPhotoPicker#43]
选择视频的时候如果这个视频在iCloud上，没在本地保存，点击预览的时候封面图闪一下之后就一片空白了，不会自动下载播放。另外，查看的图片如果是在iCloud上保存，点击预览是可以自动下载到本地的。

**Comment by LoveZYForever** [comment]
在吗?在吗? 加下我QQ294005139  我有个东西问你...

**Comment by KingQinchn** [comment]
刚看到 加你了
