### ISSUE TITLE
怎样下载iCloud照片,我现在点击iCloud提示"尚未从iCloud上下载"去相册下载完毕后选择?

### ISSUE THREAD

**Issue by Jetsond** [LoveZYForever/HXWeiboPhotoPicker#56]
刚下了demo,在真机上调试都是这个,求大佬解决..

**Comment by Jetsond** [comment]
![b52018eba48f0cf020743bb819d36e9b](https://user-images.githubusercontent.com/15120827/32264810-58c0ce04-bf1b-11e7-8170-2183ac65ecb2.png)

**Comment by LoveZYForever** [comment]
到系统相册里打开那照片系统会自动下载,右下角有个进度小圈圈

**Comment by Jetsond** [comment]
不能在选择照片的时候进行下载吗

**Comment by Jetsond** [comment]
![img_1682](https://user-images.githubusercontent.com/15120827/32265128-adc7d248-bf1c-11e7-9e8b-b9b8e14940b5.JPG)
类似于QQ这样

**Comment by blmyself** [comment]
我也遇到同样的问题，请问楼上解决了么？

**Comment by LoveZYForever** [comment]
最新版已支持在线下载iCloud上的资源
