### ISSUE TITLE
如果图片是在iCloud上，是否可以有方法下载到本地？

### ISSUE THREAD

**Issue by zhoulijun12315** [LoveZYForever/HXWeiboPhotoPicker#6]
如果图片是在iCloud上，是否可以有方法下载到本地？

**Comment by LoveZYForever** [comment]
可以的, 但是由于我没有测试数据... 所以可能会有问题

**Comment by HQL-yunyunyun** [comment]
加载iCloud上的照片会出现 Creating an image format with an unknown type is an error 这个问题

**Comment by HQL-yunyunyun** [comment]
iCloud是可以加载下来，可是当打开iCloud上的照片的时候会卡顿,估计是在下载 @LoveZYForever

**Comment by LoveZYForever** [comment]
加个好友明天上班的时候沟通一下吧
