### ISSUE TITLE
老板,纠正一下

### ISSUE THREAD

**Issue by tingyuyisheng** [LoveZYForever/HXWeiboPhotoPicker#65]
二. 安装 - Installation
Cocoapods：pod 'HXWeiboPhotoPicker' '~> 2.1.3'搜索不到库或最新版请执行pod repo update
手动导入：将项目中的“HXWeiboPhotoPicker”文件夹拖入项目中
网络图片加载使用的是SDWebImage v4.0.0
使用前导入头文件 "HXPhotoPicker.h"

你的这个pod 'HXWeiboPhotoPicker' '~> 2.1.3',少了一个标点,应该是pod 'HXWeiboPhotoPicker', '~> 2.1.3' 我今天集成你的框架,老是提示[!] Unable to find a specification for `HXWeiboPhotoPicker~> 2.1.3`

**Comment by LoveZYForever** [comment]
(°_°)…
