### ISSUE TITLE
关于引用其他第三方框架的问题

### ISSUE THREAD

**Issue by HouWan** [LoveZYForever/HXWeiboPhotoPicker#77]
您好，我发现您的库依赖于`SDWebImage`，那么假如项目使用了`CocoaPods`方式引用了`SDWebImage`，又使用了`CocoaPods`引用了您的`HXWeiboPhotoPicker`，那么这时就会出现问题，正确的方式应该在您的库里，所有引用`SDWebImage`的地方，都使用如下方式引用头文件： 

```
#if __has_include(<SDWebImage/UIImageView+WebCache.h>)
#import <SDWebImage/UIImageView+WebCache.h>
#else
#import "UIImageView+WebCache.h"
#endif

```

**Comment by LoveZYForever** [comment]
3q!
