### ISSUE TITLE
在cell上添加该控价 如何操作

### ISSUE THREAD

**Issue by haijiaoliuhao91** [LoveZYForever/HXWeiboPhotoPicker#78]

**Comment by LoveZYForever** [comment]
在cell上添加的话需要自己在manager里面添加几个数组属性记录选择的内容，然后在cell赋值里重新将选择的model 数组重新赋值刷新。这里注意有好几个数组都需要记录。
一直没时间在demo里加cell上用法的例子。等过两天看看有没有时间加下。思路就是这个样子，关于cell上加选择器已经在app上使用过了。

**Comment by LoveZYForever** [comment]
已加。

**Comment by haijiaoliuhao91** [comment]
年前我采取不复用的方式暂时实现了功能 上班后我看看你写的demo学习学习 thank you  very much
