### ISSUE TITLE
iPad上HXPhotoView不能选择

### ISSUE THREAD

**Issue by mgv5** [LoveZYForever/HXWeiboPhotoPicker#8]
建议将HXPhotoView中的- (void)actionSheet:(UIActionSheet *)actionSheet clickedButtonAtIndex:(NSInteger)buttonIndex换成- (void)actionSheet:(UIActionSheet *)actionSheet didDismissWithButtonIndex:(NSInteger)buttonIndex

**Comment by LoveZYForever** [comment]
好,可以... 问一下 iPad上可以看到系统照片?

**Comment by mgv5** [comment]
可以
